travis:
  secure:
    BINSTAR_TOKEN: Xsq1WgkyXLQ8uQnps2EtC0p7piJJ/j/cJ4GkPICbaEvue2TthUhbMpzBouJ/r30tbVbhhorY7RzU5ZKvirpNhVbLWPywebNklcKRsDZZy7KXST6HQ7zaDEJvtuYon3RHVbwV7eCR9VjtHQrFM+lZEnrMcnD4TelwNLWWd6pakNPqW4dQWO1fgXKIM5S8MHIiV9iYP6D14n2WSEE2M+jwdQnf0d0dr6Y0fWGBEzgvsQ1axh3+gqY2nMHg0qzAg6gEy6/NdPPPB88pyJCOxMBR6jLRKQC4wSljImHN30oB/hf/MoJygZ/ZtWcGtVm9RRkxGHZWls5gqjgTsgbe9RdI76Ek/F6XZoo2Uux1rKEq2CclL3+S9vvkBwohh9CZsLIDACHlEd7rzCY2r7tF1q9dkEsjsE4c4iS/LjgfQPVzgZ4yYgzkFaWlfmbiEYqxzdJP4kFtkY9WX2dH5jRVCkd/W3gp70EgDg/lUxaF0cgmNSApzdMsLczwR/vhyoYe9aifL0Raf5PxJ9fxrx6JEJsG0BJw/e3GMUoUtZxiCarbvWBo3lwPRreu2FRmhv2VENUspon5EPPmvQ+vjXsIUeqzTzxfgFw7+OtXcb9t/PM87Bc0DZUg9750t1ock6T60rXP+wJhW9klBYRyUXpfgz554d1FfbB6hyk2jBT2hJnDRFs=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
